### ISSUE TITLE
TypeError on request get_context

### ISSUE THREAD

**Issue by tophamtech** [JeanExtreme002/FlightRadarAPI#17]
Creating a very basic script as below:

```
from FlightRadar24.api import FlightRadar24API
fr_api = FlightRadar24API()

zones = fr_api.get_zones()

print(zones)
```

results in a type error:
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    zones = fr_api.get_zones()
  File "/mnt/c/Users/jimbo/Documents/dev/python/flightTracker/basic-env/lib/python3.5/site-packages/FlightRadar24/api.py", line 118, in get_zones
    zones = request.get_content()
  File "/mnt/c/Users/jimbo/Documents/dev/python/flightTracker/basic-env/lib/python3.5/site-packages/FlightRadar24/request.py", line 46, in get_content
    return json.loads(content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

I have fixed this by adding a decode at line L46 of request.py 
`return json.loads(content.decode('utf-8'))`

Is this repeatable by others? And would this fix have any knockon effects?

Thanks

**Comment by JeanExtreme002** [comment]
It's weird... I just tested the function and it's working perfectly. 

I think the problem is on response. Maybe FR24 didn't send the `Content-Encoding`. This way, nothing is done to `content`. I'm going to set the decode() method as default. Thank you very much for reporting!

**Comment by JeanExtreme002** [comment]
Oh, I understood what is going on. You are using Python 3.5. The json.loads method support binary input only in Python 3.6+.
