### ISSUE TITLE
Downloading the latest version with pip fails , however May 28 build installs

### ISSUE THREAD

**Issue by YesItsTheRealIvoie2006** [JeanExtreme002/FlightRadarAPI#40]
Hello again @JeanExtreme002 , I recently attempted to install the lib again as my laptop decided to obliterate itself so I had to reinstall everything

Unfortunately it seems that pip does not want to play nice with brotli , thus it exits without installing 

I have managed to get the May 28 2023 build working tho, pip seems to play nice with it
Please find below a verbose log of the pip install 
Thanks - Ivoie 
```
C:\Users\Ivoie>pip3 install FlightRadarAPI -v
Using pip 23.1.2 from C:\Program Files\Python311\Lib\site-packages\pip (python 3.11)
Collecting FlightRadarAPI
  Using cached FlightRadarAPI-1.3.7.tar.gz (10 kB)
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
  Collecting wheel
    Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-68.0.0 wheel-0.40.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Ivoie\AppData\Local\Temp\pip-build-env-j4v629eb\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Ivoie\AppData\Local\Temp\pip-build-env-j4v629eb\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "C:\Users\Ivoie\AppData\Local\Temp\pip-build-env-j4v629eb\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
      self).run_setup(setup_script=setup_script)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Ivoie\AppData\Local\Temp\pip-build-env-j4v629eb\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 3, in <module>
    File "C:\Users\Ivoie\AppData\Local\Temp\pip-install-k2iuhoym\flightradarapi_c3dc49f3968c447b81112f989e7b87e3\FlightRadar24\__init__.py", line 18, in <module>
      from .api import FlightRadar24API, FlightTrackerConfig
    File "C:\Users\Ivoie\AppData\Local\Temp\pip-install-k2iuhoym\flightradarapi_c3dc49f3968c447b81112f989e7b87e3\FlightRadar24\api.py", line 11, in <module>
      from .request import APIRequest
    File "C:\Users\Ivoie\AppData\Local\Temp\pip-install-k2iuhoym\flightradarapi_c3dc49f3968c447b81112f989e7b87e3\FlightRadar24\request.py", line 5, in <module>
      import brotli
  ModuleNotFoundError: No module named 'brotli'
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Program Files\Python311\python.exe' 'C:\Program Files\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\Ivoie\AppData\Local\Temp\tmp0uvkx1t_'
  cwd: C:\Users\Ivoie\AppData\Local\Temp\pip-install-k2iuhoym\flightradarapi_c3dc49f3968c447b81112f989e7b87e3
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by JeanExtreme002** [comment]
Fixed it on 1.3.8 version. Thank you!
